server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/nft?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1



mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.blockchain.pojo
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com.blockchain.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT负载中拿到开头
  tokenHead: Bearer