spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nft?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root
#    password: 123.abc
#  设置上传文件的最大容量
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql

  #  mapper-locations: classpath*:/mapper/*Mapper.xml

  mapper-locations: classpath:com/bc/mapper/xml/*.xml
  type-aliases-package: com.bc.entity